# Generated by Django 3.1.7 on 2021-08-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(upload_to='C:\\Users\\Dell\\Desktop\\Student-Management-System\\media\\'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumnail_path',
            field=models.FilePathField(path='C:\\Users\\Dell\\Desktop\\Student-Management-System\\media\\'),
        ),
    ]
