# Generated by Django 3.1.7 on 2021-08-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_client_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(upload_to='C:\\Users\\Dell\\Desktop\\Library-Management-System\\media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumnail_path',
            field=models.FilePathField(path='C:\\Users\\Dell\\Desktop\\Library-Management-System\\media'),
        ),
    ]
