# Generated by Django 3.1.7 on 2021-08-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_post_thumnail_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(upload_to='media/'),
        ),
    ]
